package com.example.service;


import java.io.FileOutputStream;
import java.util.Date;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;


public class GenaratePdf {
	    private static String FILE = "/Users/arpitadas/Documents/FirstPdf.pdf";
	    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
	            Font.BOLD);
	    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
	            Font.NORMAL, BaseColor.RED);
	    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
	            Font.BOLD);
	    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
	            Font.BOLD);

	    public static void main(String[] args) {
	        try {
	            Document document = new Document();
	            PdfWriter.getInstance(document, new FileOutputStream(FILE));
	            document.open();
	            addMetaData(document);
	            addTitlePage(document);
	            document.close();
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
	    }

	    // iText allows to add metadata to the PDF which can be viewed in your Adobe
	    // Reader
	    // under File -> Properties
	    private static void addMetaData(Document document) {
	        document.addTitle("Invoice");
	        document.addSubject("For below Subscrption");
	        document.addKeywords("Java, PDF, iText");
	        document.addAuthor("Arpita Das");
	        document.addCreator("Arpita Das");
	    }

	    private static void addTitlePage(Document document)
	            throws DocumentException {
	        Paragraph preface = new Paragraph();
	        // We add one empty line
	        addEmptyLine(preface, 1);
	        // Lets write a big header
	        preface.add(new Paragraph("Invoice of Current Subscription", catFont));

	        addEmptyLine(preface, 1);
	        // Will create: Report generated by: _name, _date
	        preface.add(new Paragraph(
	                "Report generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
	                smallBold));
	        addEmptyLine(preface, 4);
	        preface.add(new Paragraph(
	                "Amount" + "656566",
	                smallBold));
	        addEmptyLine(preface, 5);
	        preface.add(new Paragraph(
	                "Subscription Type " + "tiyuyuuiou",
	                smallBold));
	        addEmptyLine(preface, 6);
	        preface.add(new Paragraph(
	                "Invoice Date/Dates " + "yuyuiu",
	                smallBold));
	        
	        addEmptyLine(preface, 7);
	        preface.add(new Paragraph(
	                "This document describes something which is very important ",
	                smallBold));

	        //addEmptyLine(preface, 8);

	        preface.add(new Paragraph(
	                "This document is a preliminary version and not subject to your license agreement or any other agreement with EazyPay.com ;-).",
	                redFont));

	        document.add(preface);
	    }


	    private static void addEmptyLine(Paragraph paragraph, int number) {
	        for (int i = 0; i < number; i++) {
	            paragraph.add(new Paragraph(" "));
	        }
	    }
}
